### ISSUE TITLE
impl CanTween for MyType

### ISSUE THREAD

**Issue by haselkern** [HannesMann/keyframe#3]
I'm trying to implement CanTween manually for a type that does not work with the derive macro.
~~~rust
impl CanTween for MyType {
    fn ease(from: Self, to: Self, time: impl Float) -> Self {
        unimplemented!()
    }
}
~~~
The `keyframe::Float` trait is private however, making it impossible to implement it like that.

How could I implement CanTween for MyType?

**Comment by HannesMann** [comment]
`Float` is a part of the `num_traits` crate. Could you try this?
```
impl CanTween for MyType {
    fn ease(from: Self, to: Self, time: impl keyframe::num_traits::Float) -> Self {
        unimplemented!()
    }
}
```

**Comment by haselkern** [comment]
That works perfectly, thank you!
