### ISSUE TITLE
Second example showcasing frame-by-frame animation

### ISSUE THREAD

**Issue by PSteinhaus** [HannesMann/keyframe#5]
First off: Thank you for creating this library!
Recently, [we've been discussing adding an animation feature using tweens and keyframes to ggez](https://github.com/ggez/ggez/issues/910), or maybe better the ggez-goodies. And now I've stumbled upon this and am absolutely delighted that someone already did all the hard work of implementing all of this!

Now I really want to use keyframe to create an example showcasing classic frame-by-frame animation using ggez's spritebatch functionality.
The basic idea would be to create a spritebatch from an image holding all the animation frames next to each other and to then step through these frames by setting `DrawParam::src` accordingly, using keyframe.
I'd probably do that by creating keyframes and using something like the `Step` function.

Now my main question is: Do we want to add this example as a second example here? Or would it be better if I just added it to ggez directly?

**Comment by HannesMann** [comment]
Either option would work for me. If there's already a collection of ggez examples put it there otherwise just send a pull request and I'll add your example here. The library was created as a learning exercise for Rust and ggez so it's not like it would be out of place. :)

**Comment by PSteinhaus** [comment]
Alright, then we'll put it next to our other examples!
